import { Geist, Geist_Mono } from "next/font/google";
import Image from "next/image";
import "./globals.css";
import Navbar from './navbar.js'
// import MouseFollower from "./follower";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Akash Shinde",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="my-5 flex justify-center">
          <Navbar />
        </div>
        <main className="container mx-auto mb-10 p-5 w-full sm:w-1/2 sm:border">
          {children}
          {/* <MouseFollower /> */}
        </main>
        <div className="fixed bottom-5 left-5">
          <Image src={`${process.env.NODE_ENV === 'production' ? '/website/song-bg-crop.gif' : '/song-bg-crop.gif'}`} height={200} width={200} alt="gif" className="hidden sm:block" />
        </div>
        <footer className="fixed bottom-0 left-0 w-screen flex items-center justify-center mb-2">
          <p className="text-xs">Made with NextJS by Akash Shinde @ 2025</p>
        </footer>
      </body>
    </html>
  );
}
